[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.EarlyStopping>
[instantiate_callbacks] Instantiating callback <lightning.pytorch.callbacks.LearningRateMonitor>
Epoch 1: 100%|██████████| 2/2 [00:00<00:00, 10.07it/s, loss=0.341, v_num=1kfd]
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/fabric/plugins/environments/slurm.py:166: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python my_experiment.py ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:612: UserWarning: Checkpoint directory checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [MIG-c520cbb9-133b-5a16-81a3-2b18e3f38047]
  | Name  | Type        | Params
--------------------------------------
0 | model | ByteNetArch | 1.0 M
--------------------------------------
1.0 M     Trainable params
0         Non-trainable params
1.0 M     Total params
4.104     Total estimated model params size (MB)
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/n/home10/pafischer/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:1600: PossibleUserWarning: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 0, global step 1: 'val_loss' reached 0.33248 (best 0.33248), saving model to 'checkpoints/epoch=0-step=1-val_loss=0.3325-v2.ckpt' as top 1
Epoch 1, global step 2: 'val_loss' reached 0.22236 (best 0.22236), saving model to 'checkpoints/epoch=1-step=2-val_loss=0.2224-v1.ckpt' as top 2
Epoch 2, global step 3: 'val_loss' reached 0.17747 (best 0.17747), saving model to 'checkpoints/epoch=2-step=3-val_loss=0.1775.ckpt' as top 3
Epoch 3, global step 4: 'val_loss' reached 0.15647 (best 0.15647), saving model to 'checkpoints/epoch=3-step=4-val_loss=0.1565-v1.ckpt' as top 4
Epoch 4, global step 5: 'val_loss' reached 0.14200 (best 0.14200), saving model to 'checkpoints/epoch=4-step=5-val_loss=0.1420.ckpt' as top 5

Epoch 6:   0%|          | 0/2 [00:00<?, ?it/s, loss=0.23, v_num=1kfd]
Epoch 6, global step 7: 'val_loss' reached 0.11667 (best 0.11667), saving model to 'checkpoints/epoch=6-step=7-val_loss=0.1167.ckpt' as top 7
Epoch 7, global step 8: 'val_loss' reached 0.10302 (best 0.10302), saving model to 'checkpoints/epoch=7-step=8-val_loss=0.1030.ckpt' as top 8
Epoch 8, global step 9: 'val_loss' reached 0.09283 (best 0.09283), saving model to 'checkpoints/epoch=8-step=9-val_loss=0.0928-v2.ckpt' as top 9
Epoch 10:  50%|█████     | 1/2 [00:00<00:00,  8.70it/s, loss=0.173, v_num=1kfd]
Validation: 0it [00:00, ?it/s]
Epoch 10, global step 11: 'val_loss' reached 0.07774 (best 0.07774), saving model to 'checkpoints/epoch=10-step=11-val_loss=0.0777-v1.ckpt' as top 11
Epoch 11, global step 12: 'val_loss' reached 0.07330 (best 0.07330), saving model to 'checkpoints/epoch=11-step=12-val_loss=0.0733-v2.ckpt' as top 12
Epoch 12, global step 13: 'val_loss' reached 0.06833 (best 0.06833), saving model to 'checkpoints/epoch=12-step=13-val_loss=0.0683-v3.ckpt' as top 13
Epoch 13, global step 14: 'val_loss' reached 0.06602 (best 0.06602), saving model to 'checkpoints/epoch=13-step=14-val_loss=0.0660-v3.ckpt' as top 14


Epoch 19:   0%|          | 0/2 [00:00<?, ?it/s, loss=0.128, v_num=1kfd]
Epoch 15, global step 16: 'val_loss' reached 0.06102 (best 0.06102), saving model to 'checkpoints/epoch=15-step=16-val_loss=0.0610-v2.ckpt' as top 16
Epoch 16, global step 17: 'val_loss' reached 0.06088 (best 0.06088), saving model to 'checkpoints/epoch=16-step=17-val_loss=0.0609.ckpt' as top 17
Epoch 17, global step 18: 'val_loss' reached 0.05917 (best 0.05917), saving model to 'checkpoints/epoch=17-step=18-val_loss=0.0592-v1.ckpt' as top 18

Epoch 19: 100%|██████████| 2/2 [00:00<00:00,  4.60it/s, loss=0.125, v_num=1kfd]
Epoch 19, global step 20: 'val_loss' reached 0.05730 (best 0.05730), saving model to 'checkpoints/epoch=19-step=20-val_loss=0.0573-v2.ckpt' as top 20
`Trainer.fit` stopped: `max_epochs=20` reached.